name: install and cache dependencies
description: install python packages (pip) from requirements and requirements_dev, and cache them
inputs:
  python-version:
    required: false
    default: '3.10'

runs:
  using: composite
  steps:
    - name: python setup
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: 'requirements*.txt'

    - name: dependencies
      run: |
        python -m pip install .
        python -m pip install -r requirements_dev.txt
      shell: bash
