name: polvol

services:
  backend:
    build:
      context: backend
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 500M
    restart: on-failure:3
    volumes:
      - app_data:/data
    ports:
      - 8000:8000
    networks:
      - app_net

  frontend:
    depends_on:
      - backend
    build:
      context: frontend
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 500M
    restart: on-failure:3
    ports:
      - 5173:80
    networks:
      - app_net

volumes:
  app_data:

networks:
  app_net:
