name: polvol

services:
  backend:
    build:
      context: backend
    volumes:
      - app_data:/data
    ports:
      - 8000:8000
    networks:
      - appnet

  frontend:
    depends_on:
      - backend
    build:
      context: frontend
    ports:
      - 5173:80
    networks:
      - appnet

volumes:
  app_data:

networks:
  app_net:
