name: Build Images and Release

on:
  workflow_dispatch:
    inputs:
      backend_version:
        type: string
        required: true
      frontend_version:
        type: string
        required: true

jobs:
  lint_and_test:
    uses: ./.github/workflows/lint_and_test.yml

  build_backend:
    name: Build Docker image for backend
    needs: lint_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:backend"
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/polvol-backend:${{ inputs.backend_version }}

  build_frontend:
    name: Build Docker image for frontend
    needs: lint_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:frontend"
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/polvol-frontend:${{ inputs.frontend_version }}

  release:
    name: Release newest verion on Azure Container App
    needs:
      - build_backend
      - build_frontend
    runs-on: ubuntu-latest
    steps:
      - run: echo "just sitting for now..."
