name: Check MyPy and Black Formatting for Python and Formatting for Js
on: [push, workflow_dispatch, workflow_call]
jobs:
  Pyhton:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - uses: ./.github/actions/manage_dependencies
      #   with:
      #     path: "backend"
      #     python-version: "3.10"
      - name: manage dependencies
        run: |
          cd backend
          python -m pip install -r requirements.txt
          python -m pip install -r requirements_dev.txt
      - name: check black and mypy
        run: |
          python -m black --check backend/src
          python -m mypy backend/src

  JS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install Node.js dependencies
        run: |
          cd frontend
          npm ci
          npm install prettier
      - name: run lint check on js
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true

  # test-unit:
  #   strategy:
  #     matrix:
  #       py_ver: ['3.9', '3.10', '3.11', '3.13']
  #       os: [ubuntu-latest, windows-latest]
  #   name: run unit tests
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/manage_dependencies
  #       with:
  #         python-version: ${{ matrix.py_ver }}
  #     - name: test code
  #       id: test
  #       run: python -m pytest tests/unit_tests
  #     - name: test artifacts
  #       if: failure() && steps.test.outcome == 'failure'
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: log-unit-tests
  #         path: logs-unit

  # test-module:
  #   strategy:
  #     matrix:
  #       py_ver: ['3.9', '3.10', '3.11', '3.13']
  #       os: [ubuntu-latest, windows-latest]
  #   name: run module tests
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/manage_dependencies
  #       with:
  #         python-version: ${{ matrix.py_ver }}
  #     - name: test code
  #       id: test
  #       run: python -m pytest tests/module_tests
  #     - name: test artifacts
  #       if: failure() && steps.test.outcome == 'failure'
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: log-module-tests
  #         path: logs-module
